language: node_js
cache:
  directories:
    - node_modules
node_js:
  - node
script:
  - npm run test
after_success: 
  - bash docker_push.sh 
services: 
  - docker
addons:
  ssh_known_hosts: 116.202.28.78
before_install:
  - openssl aes-256-cbc -K $encrypted_2a024576628c_key -iv $encrypted_2a024576628c_iv -in id_rsa.enc -out id_rsa -d
  - docker build -t "bldb" .
  - docker run --name "bldb" -p 9090:9090 bldb
  - docker ps a   
